### ISSUE TITLE
Writing ZonedDateTime 

### ISSUE THREAD

**Issue by alexec** [ebowman/api-first-hand#56]
When a JSON string is written, the whole of the `ZonedDateTime` is written using (I think) the default `toString`:

~~~
"processingDate":{"offset":{"totalSeconds":0,"id":"Z","rules":{"transitions":[],"transitionRules":[],"fixedOffse...
~~~

Could I request a normal formatted date is written instead?

**Comment by slavaschmidt** [comment]
+1

**Comment by LappleApple** [comment]
Hi @alexec, feel free to make a PR to address this. :)
