### ISSUE TITLE
HTTP response headers

### ISSUE THREAD

**Issue by alexec** [ebowman/api-first-hand#59]
I'm not clear how these work.  It the spec I have the following:

~~~
      responses:
        200:
          description: Success
          headers:
            CorrelationId:
              type: string
              pattern: ^[A-Za-z0-9]{32}$
~~~

But none of the generated code allows you to return this :(

**Comment by slavaschmidt** [comment]
@alexec Hey, thanks for mentioned this. Indeed, it seems like we forgot to implement this functionality altogether.
