### ISSUE TITLE
JSON schema enums produce code that does not compile.

### ISSUE THREAD

**Issue by alexec** [ebowman/api-first-hand#62]
I'll update when I have stack trace.

**Comment by alexec** [comment]
Workaround:

Cannot use the `enum` keyword. Remove, replace with `pattern`.

Good:

    "foobar": {
        "type": "string, 
        "pattern: "(cash|accruals)"
    }

Bad:

    "foobar": {
        "type": "string, 
        "enum": [
            "cash", 
            "accruals"
        ]
    }

**Comment by LappleApple** [comment]
Hi @alexec, if you'd like to make a PR to address the bug that would be great.

**Comment by slavaschmidt** [comment]
Should be resolved with https://github.com/zalando/api-first-hand/pull/73

**Comment by s12v** [comment]
@slavaschmidt, this seems to be fixed/merged/released?

**Comment by slavaschmidt** [comment]
@s12v, yeah, this should be fixed in 0.2.0, I had no time to manually verify that it works or add the example to the scripted test, therefore not closing the ticket yet.
